"""Remove avatar_path column from users table

Revision ID: 96405639a9b4
Revises: c33c05502a7b
Create Date: 2025-12-10 15:13:50.690753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96405639a9b4'
down_revision = 'c33c05502a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))

    # ### end Alembic commands ###